### ISSUE TITLE
Voices out of sync

### ISSUE THREAD

**Issue by oli-ver** [jackkinsella/midi-to-part-mp3s#1]
Thank you for providing this script. I tested it with "Da unten im Tale - Johannes Brahms" from here: http://www2.cpdl.org/wiki/index.php/Da_unten_im_Tale,_Deutsche_Volklieder_WoO_35,5_(Johannes_Brahms).

I created the midi with MuseScore from the MusicXML file, because the midi file provided for the download does not separate the voices but is a piano version.

Unfortunatley the voices seem to be out of sync in the mp3 files. Did you face similar issues? This is the version I used: [Da unten im Tale - Brahms.mid.zip](https://github.com/jackkinsella/midi-to-part-mp3s/files/3269465/Da.unten.im.Tale.-.Brahms.mid.zip)

I had to remove the default for `--common-solo-tracks`, because the script did not allow not to have one.

I also changed the instrument to piano because the sync problem is better to hear with this instrument.

[alle.mp3.zip](https://github.com/jackkinsella/midi-to-part-mp3s/files/3269467/alle.mp3.zip)

**Comment by jackkinsella** [comment]
I was able to reproduce the error using the midi file you provided. But this is my first time seeing the sync issue (but only after a sample size of about 5 tracks).

I'm not sure exactly what causes the difference, but I noticed the midi file you sent me was structured differently to the ones I've previously worked with. Specifically, the first track you sent me _mixes_  meta time signature messages with note_on messages, whereas the midi files I've worked with before split apart all the special midi events to a separate channel (usually 0) that does not contain any note_on events.

You can see these messages with something like [message for message in midi_data.tracks[0]]

My intuition is that the problem is related to how this script handles midi files structured in this way.

(Also, I was able to rule out any issues related to the synthesizer by running `fluidsynth soundfonts/timbres-of-heaven.sf2 Da\ unten\ im\ Tale\ -\ Brahms.mid`)

**Comment by oli-ver** [comment]
I created the midi from the MusicXML with [MuseScore](https://musescore.org/). Actually this seems to be a MuseScore bug. The conversion obviously does not return a valid midi file. I just converted the MusicXML with the python library music21 and it worked like a charm!

I will create a pull request for that. I enhanced your script to support both formats, so it's actually a nice feature because MusicXML is also a common format.

**Comment by oli-ver** [comment]
I will wait with the pull request until you merged the other one. It's based on the master branch after my changes.

**Comment by jackkinsella** [comment]
> I created the midi from the MusicXML with [MuseScore](https://musescore.org/). Actually this seems to be a MuseScore bug. The conversion obviously does not return a valid midi file. 

Just to double check things: What evidence do we have so far that this is a MuseScore bug? 

### Arguments it might not be a bug
* Garage Band plays it perfectly despite the issues
* MuseScore is a well-established piece of software and I would be inclined to trust their output (at least if you were using in a standard way)

### Arguments it is a bug
* seems to go against this description of the midi format
<img width="1415" alt="Screen Shot 2019-06-13 at 17 13 29" src="https://user-images.githubusercontent.com/151206/59444752-afabeb00-8dfe-11e9-9f57-68dfbf7e167a.png">

**Comment by oli-ver** [comment]
I think there is a very long and emotional thread discussing exactly this issue:

https://musescore.org/en/node/207346

I think as converting the file with music21 works perfectly I would just leave it like that for now.

**Comment by jackkinsella** [comment]
well that settles it — thanks for digging that one up!

**Comment by jackkinsella** [comment]
I tried a bunch of other midi files today and many of them seemed to have been compiled with MuseScore's broken format. Therefore I think it would be worthwhile for me to see if I can extend the script to handle broken midis too — the user experience would be better.

**Comment by oli-ver** [comment]
I also noticed that today with a MusicXML. Even after converting it with

**Comment by oli-ver** [comment]
This is what I tried with the converted midi after converting it from MusicXML.

The idea was just to leave the meta messages in the track and no NOTE_ON and NOTE_OFF messages. I am not so familiar with midi, so it's possible that I just removed the wrong or not all necessary messages.

For now I will rather finish #3 than working on this.

```python
import copy

def convert_music_xml_to_midi(file_path: str) -> str:
  """Converts a MusicXML file to midi
  
  Arguments:
      file_path {str} -- file path of the the MusicXML file
  
  Returns:
      str -- path of the converted midi file after conversion
  """
  converted_file_path = output_directory + '/temp.midi'
  score: music21.stream.Score = music21.converter.parse(file_path)
  midi_file: music21.midi.MidiFile = music21.midi.translate.streamToMidiFile(score)
  track0_contains_notes = False
  track0 = midi_file.tracks[0]
  for event in track0.events:
    if event.type == 'NOTE_ON':
      print("Notes on track 0 found. Will duplicate this track and create an additional track only including meta information")
      track0_contains_notes = True
      break
  track0_new = copy.copy(track0)
  for event in track0_new.events:
    if event.type.startswith('NOTE'):
      track0_new.events.remove(event)
  track0_new.updateEvents()
  midi_file.tracks.insert(0, track0_new)
  for i in range(len(midi_file.tracks)):
    track = midi_file.tracks[i]
    track.index = i+1
  midi_file.open(converted_file_path, 'wb')
  midi_file.write()
  midi_file.close()
  return converted_file_path
```

**Comment by jackkinsella** [comment]
Thanks — I'm taking a look at this now. I have some midi files that convert successfully on my computer so I'll compare the tracks to the ones with sync problems to see if I can spot any difference.

**Comment by jackkinsella** [comment]
OK I've made some progress here https://github.com/jackkinsella/midi-to-part-mp3s/tree/handle-musescore-midis — it's sounding nearly perfect on the previously broken test track of Schubert Deutsche Messe. The Brahms is better but still somehow off though.
