### ISSUE TITLE
Feature: Support more voices

### ISSUE THREAD

**Issue by oli-ver** [jackkinsella/midi-to-part-mp3s#3]
Currently the script only allows to create mp3 files for SATB. It would be good to add more flexibility and make the voices configurable. I would suggest to enhance the argument parser with `nargs='*'` for all voices and set no defaults anymore. 

This way the script can be used for all types of choirs and midi / MusicXML files:
- mixed choir SATB or SSAATTBB
- women's chor SSAA or SSA
- men's choir TTBB or ATBB

What do you think? There will be some code changes, but it would be very helpful as I need SSAATTBB quite often.

**Comment by jackkinsella** [comment]
Yes 100% up for this. Also have a similar need as my choir will be working on some pieces for 8 voices soon.
